# Generated by Django 4.0.4 on 2022-07-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'пост'},
        ),
    ]
